spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "${DB_URL:jdbc:postgresql://${POSTGRESQL_HOST:127.0.0.1}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE:budlog_dev}}"

app:
  access:
    enabled: ${APP_ACCESS_ENABLED:false}
