COMMENT ON TABLE baby_profile IS '宝宝档案，存储宝宝基本资料';
COMMENT ON COLUMN baby_profile.id IS '宝宝档案主键';
COMMENT ON COLUMN baby_profile.name IS '宝宝昵称';
COMMENT ON COLUMN baby_profile.birth_time IS '出生时间';
COMMENT ON COLUMN baby_profile.timezone IS '宝宝所在时区';
COMMENT ON COLUMN baby_profile.note IS '备注';
COMMENT ON COLUMN baby_profile.created_at IS '创建时间';
COMMENT ON COLUMN baby_profile.updated_at IS '最后更新时间';

COMMENT ON TABLE custom_milestone IS '自定义里程碑，存储宝宝的关键日期';
COMMENT ON COLUMN custom_milestone.id IS '自定义里程碑主键';
COMMENT ON COLUMN custom_milestone.baby_id IS '关联的宝宝档案 ID';
COMMENT ON COLUMN custom_milestone.title IS '里程碑标题';
COMMENT ON COLUMN custom_milestone.target_time IS '目标日期时间';
COMMENT ON COLUMN custom_milestone.note IS '备注';
COMMENT ON COLUMN custom_milestone.client_request_id IS '客户端请求唯一标识，用于幂等写入';
COMMENT ON COLUMN custom_milestone.created_at IS '创建时间';
COMMENT ON COLUMN custom_milestone.updated_at IS '最后更新时间';
COMMENT ON COLUMN custom_milestone.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE feeding_record IS '喂养记录，存储宝宝每次喂养的明细';
COMMENT ON COLUMN feeding_record.id IS '喂养记录主键';
COMMENT ON COLUMN feeding_record.baby_id IS '关联的宝宝档案 ID';
COMMENT ON COLUMN feeding_record.feeding_type IS '喂养类型：BREAST_DIRECT=母乳亲喂，BREAST_BOTTLE=母乳瓶喂，FORMULA_BOTTLE=奶粉瓶喂';
COMMENT ON COLUMN feeding_record.breast_side IS '乳房侧别：LEFT=左侧，RIGHT=右侧，BOTH=两侧';
COMMENT ON COLUMN feeding_record.start_time IS '喂养开始时间';
COMMENT ON COLUMN feeding_record.end_time IS '喂养结束时间';
COMMENT ON COLUMN feeding_record.amount_ml IS '喂养量，单位毫升';
COMMENT ON COLUMN feeding_record.note IS '备注';
COMMENT ON COLUMN feeding_record.client_request_id IS '客户端请求唯一标识，用于幂等写入';
COMMENT ON COLUMN feeding_record.created_at IS '创建时间';
COMMENT ON COLUMN feeding_record.updated_at IS '最后更新时间';
COMMENT ON COLUMN feeding_record.deleted_at IS '软删除时间，NULL 表示未删除';
COMMENT ON CONSTRAINT ck_feeding_type ON feeding_record IS '限制喂养类型为母乳亲喂、母乳瓶喂或奶粉瓶喂';
COMMENT ON CONSTRAINT ck_breast_side ON feeding_record IS '限制乳房侧别为空、左侧、右侧或两侧';
COMMENT ON CONSTRAINT ck_feeding_time ON feeding_record IS '保证喂养结束时间不早于开始时间';
COMMENT ON CONSTRAINT ck_feeding_amount ON feeding_record IS '限制喂养量为空或大于 0 且不超过 1000 毫升';
COMMENT ON INDEX idx_feeding_baby_start IS '加速按宝宝和开始时间倒序查询未删除的喂养记录';

COMMENT ON TABLE diaper_record IS '尿布记录，存储宝宝排尿和排便情况';
COMMENT ON COLUMN diaper_record.id IS '尿布记录主键';
COMMENT ON COLUMN diaper_record.baby_id IS '关联的宝宝档案 ID';
COMMENT ON COLUMN diaper_record.record_type IS '记录类型：PEE=排尿，POOP=排便，BOTH=排尿并排便';
COMMENT ON COLUMN diaper_record.record_time IS '记录发生时间';
COMMENT ON COLUMN diaper_record.note IS '备注';
COMMENT ON COLUMN diaper_record.client_request_id IS '客户端请求唯一标识，用于幂等写入';
COMMENT ON COLUMN diaper_record.created_at IS '创建时间';
COMMENT ON COLUMN diaper_record.updated_at IS '最后更新时间';
COMMENT ON COLUMN diaper_record.deleted_at IS '软删除时间，NULL 表示未删除';
COMMENT ON CONSTRAINT ck_diaper_type ON diaper_record IS '限制记录类型为排尿、排便或两者同时发生';
COMMENT ON INDEX idx_diaper_baby_time IS '加速按宝宝和发生时间倒序查询未删除的尿布记录';

COMMENT ON TABLE todo_task IS '待办任务，存储与宝宝相关的提醒事项';
COMMENT ON COLUMN todo_task.id IS '待办任务主键';
COMMENT ON COLUMN todo_task.baby_id IS '关联的宝宝档案 ID';
COMMENT ON COLUMN todo_task.title IS '任务标题';
COMMENT ON COLUMN todo_task.description IS '任务描述';
COMMENT ON COLUMN todo_task.due_time IS '任务到期时间';
COMMENT ON COLUMN todo_task.remind_time IS '任务提醒时间';
COMMENT ON COLUMN todo_task.status IS '任务状态：TODO=待办，DONE=已完成，CANCELED=已取消';
COMMENT ON COLUMN todo_task.completed_at IS '任务完成时间';
COMMENT ON COLUMN todo_task.client_request_id IS '客户端请求唯一标识，用于幂等写入';
COMMENT ON COLUMN todo_task.created_at IS '创建时间';
COMMENT ON COLUMN todo_task.updated_at IS '最后更新时间';
COMMENT ON COLUMN todo_task.deleted_at IS '软删除时间，NULL 表示未删除';
COMMENT ON CONSTRAINT ck_task_status ON todo_task IS '限制任务状态为待办、已完成或已取消';
COMMENT ON CONSTRAINT ck_task_reminder ON todo_task IS '保证提醒时间不晚于任务到期时间';
COMMENT ON INDEX idx_task_baby_status_due IS '加速按宝宝、状态和到期时间查询未删除的待办任务';
COMMENT ON INDEX idx_task_status_remind IS '加速按状态和提醒时间查询未删除的待办任务';

COMMENT ON TABLE app_setting IS '应用设置，存储全局喂养间隔和提醒配置';
COMMENT ON COLUMN app_setting.id IS '应用设置主键，默认配置使用 1';
COMMENT ON COLUMN app_setting.default_feeding_interval_min IS '默认喂养间隔，单位分钟';
COMMENT ON COLUMN app_setting.feeding_interval_anchor IS '喂养间隔计算锚点，当前仅支持 START（开始时间）';
COMMENT ON COLUMN app_setting.reminder_sound_enabled IS '是否启用提醒声音';
COMMENT ON COLUMN app_setting.reminder_vibrate_enabled IS '是否启用振动提醒';
COMMENT ON COLUMN app_setting.updated_at IS '最后更新时间';
COMMENT ON CONSTRAINT ck_feeding_interval ON app_setting IS '限制默认喂养间隔为 30 至 720 分钟';
COMMENT ON CONSTRAINT ck_feeding_anchor ON app_setting IS '限制喂养间隔计算锚点为开始时间';
